name: HiFiNiCN

on:
  workflow_dispatch:         # 手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sign in
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
          HIFINICNCOOKIE: ${{secrets.HIFINICNCOOKIE}}
        run: |
          ping -c 5 www.hifini.com.cn
          python hifinicn_sign.py
